spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookmyshow
    username: postgres
    password: Root@123#
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
